### ISSUE TITLE
登录请求 500 错误

### ISSUE THREAD

**Issue by Mysels** [ZimoLoveShuang/wisedu-unified-login-api#12]
`org.jsoup.HttpStatusException: HTTP error fetching URL. Status=500, URL=https://**.campusphere.net/portal/login?ticket=***
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:762)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:707)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:297)
        at wiki.zimo.wiseduunifiedloginapi.process.CasLoginProcess.casSendLoginData(CasLoginProcess.java:198)
        at wiki.zimo.wiseduunifiedloginapi.process.CasLoginProcess.login(CasLoginProcess.java:165)
        at wiki.zimo.wiseduunifiedloginapi.service.impl.LoginServiceImpl.login(LoginServiceImpl.java:72)
        at wiki.zimo.wiseduunifiedloginapi.controller.ApiController.login(ApiController.java:38)
`

**Comment by ZimoLoveShuang** [comment]
Maybe you should provide your school, account, password and other information so that I can test and fix the bug. In order to protect privacy, it is recommended to send it privately. If you don't mind, you can scan the QR code and buy me a cup of milk tea.

**Comment by Mysels** [comment]
https://github.com/ZimoLoveShuang/wisedu-unified-login-api/blob/07092a70bf16361bea483dffc41888908dc6b2c7/src/main/java/wiki/zimo/wiseduunifiedloginapi/process/CasLoginProcess.java#L193

在此位置附加 Jsoup 附加选项并将提交方法改为 GET 即可修复
`                    .ignoreHttpErrors(true)
                    .method(Connection.Method.GET)
`

**Comment by Mysels** [comment]
@ZimoLoveShuang
